### ISSUE TITLE
Utilize new cimg docker image executor

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/go-orb#1]
https://github.com/CircleCI-Public/go-orb/blob/master/orb.yml#L14

Update language orbs to utilize the new cimg

**Dockerhub:** https://hub.docker.com/u/cimg
**cimg beta announcement:** https://discuss.circleci.com/t/new-convenience-image-alpha-preview-ready-for-testing/31364

Ensure tags are parameterized.

Any PRs made in service of this issue will be held until cimg docker images are ready for release.

**Comment by caseydbrown** [comment]
I would love to handle this.

**Comment by felicianotech** [comment]
Done in #3.
