### ISSUE TITLE
Add issue and pull request template

### ISSUE THREAD

**Issue by meanmachin3** [CircleCI-Public/go-orb#10]
We could add this to have consistency across all other orbs project
 I would like to pick this up. Please consider adding the orbtoberfest label on the issue

**Comment by amithkk** [comment]
Mind if I take this?
PS. Could you please add the orbtoberfest and hacktoberfest tags to this issue?

**Comment by meanmachin3** [comment]
@amithkk I'm not the maintainer. I'm waiting for the issue to be assigned to me

**Comment by meanmachin3** [comment]
@KyleTryon Done ✅
