### ISSUE TITLE
Destructure Orb

### ISSUE THREAD

**Issue by KyleTryon** [CircleCI-Public/go-orb#2]
Destructure the orb to more easily add components in the future.
https://circleci.com/docs/2.0/local-cli/#packing-a-config

This can also be accomplished with the Orb Starter Kit:
https://github.com/CircleCI-Public/orb-starter-kit

**Comment by fortrieb** [comment]
Hi, i would take this issue if nobody is already working on it?

**Comment by felicianotech** [comment]
Addressed in #4.
