### ISSUE TITLE
Does the caching actually works by default?

### ISSUE THREAD

**Issue by lubieniebieski** [CircleCI-Public/go-orb#31]
hey @felicianotech !

I'm not a golang guy, but I'm trying to build setup for a go-based project.

I'm struggling with caching right now, as I see that when "restore cache" step kicks in, the output is pretty much the same all the time:

```
Found a cache from build 4424 at go-mod-dp7+cumnSitrbWvycofIdkqN1rYyAJhzy06GVfbq3_Y=
Size: 32 B
Cached paths:
  * /home/circleci/project/$GOPATH/pkg/mod
```

I thought that this was my mistake, but 32 B doesn't seem to be a valid size, is it? I've found out that the integration tests provided in your repo [prints out a similar output](https://app.circleci.com/pipelines/github/CircleCI-Public/go-orb/62/workflows/c1a1e5ad-a8b7-48a9-a38c-6f62b95f6941/jobs/137/parallel-runs/0/steps/0-102).

Can you confirm whether it's a bug or not? 

Cheers Ricardo, thanks for your work on this orb anyway! 💪

**Comment by felicianotech** [comment]
Hi @lubieniebieski. Are you able to provide your CircleCI config so I can see how you're using the orb?

**Comment by lubieniebieski** [comment]
thanks @felicianotech, I'll provide you with the config file outside of this PR!
