### ISSUE TITLE
Default branch needs renaming

### ISSUE THREAD

**Issue by FelicianoTech** [CircleCI-Public/go-orb#60]

**Comment by david-montano-circleci** [comment]
Hello @FelicianoTech . Could you please provide more information about this?
We understand some of the arguments to move away from the `master` name convention. But this is not a strong argument yet to move away from the name for us. Please provide your thoughts about this.
Thank you!

**Comment by FelicianoTech** [comment]
I opened this when I was a CircleCI employee. This issue is of no concern to me now.
