### ISSUE TITLE
feat: Allow `test` job to support JUnit test output

### ISSUE THREAD

**Issue by adamdmharvey** [CircleCI-Public/go-orb#63]
We use the Go orb to simplify some of our Golang repo mechanics, but we don't use the `test` job because it doesn't let us specify JUnit output.

We like getting the JUnit output because it intentionally uses the features of CircleCI to better elevate our test results, and gives us data in Test Insights.

<img width="784" alt="image" src="https://user-images.githubusercontent.com/33203301/198685033-4c3f899b-14a5-44db-9bdf-720f68eae34e.png">

For example, rather than using the orb out of the box right now,

```yaml
- go/test:
    covermode: atomic
    failfast: true
    race: true
```

which provides no test output. Instead, we use a regular command and run:

```yaml
- run:
    command: gotestsum --junitfile test-results/unit-tests.xml -- -covermode=atomic -coverprofile=test-results/coverage.out
````

And then using:

```yaml
 - store_test_results:
           path: test-results
```

Would be great if there was a flag to pass into the test job to sort of do this "automatically" within the test job.

**Comment by david-montano-circleci** [comment]
Hello @adamdmharvey . The latest version of the go-orb includes a gotestsum command that you can use to generate junit xml coverage reports. [See](https://github.com/CircleCI-Public/go-orb/releases/tag/v2.2.0).
