### ISSUE TITLE
Doesn't support version `1.21`

### ISSUE THREAD

**Issue by yz89122** [CircleCI-Public/go-orb#74]
Error Log:

```
Installing the requested version of Go.
curl: (22) The requested URL returned error: 404

gzip: stdin: unexpected end of file
tar: Child returned status 1
tar: Error is not recoverable: exiting now

Exited with code exit status 2
```

Seems like this URL will respond a 404 `https://dl.google.com/go/go1.21.linux-amd64.tar.gz`.
But `https://dl.google.com/go/go1.20.linux-amd64.tar.gz` will not.

**Comment by felicianotech** [comment]
1.21 is not a version of Go.

Starting with the most recent release, the Go Team has finally started doing proper SemVer releases. The first for this release is `1.21.0` not `1.21`.

**Comment by yz89122** [comment]
How about to provide a way to allow us to use the latest patch version? E.g., `1.21` means latest patch version of `1.21`, i.g. `1.21.0` right now, and `1.21.1` when the next patch version released. Because I don't want to open a PR for each patch version(and for each repo), but I want to use the latest patch version automatically. I guess the need is common.

**Comment by david-montano-circleci** [comment]
Hello @yz89122 . The `go.mod` file in each go project also references the `minimum version of Go required by the current module.` [see](https://go.dev/doc/modules/gomod-ref).
This means that if there is a new patch version, you will have to create a PR to at least change that file.
For best practices in CICD pipelines, we think that it is not a good idea to use tags like `latest` or a way to point to the latest patch version given that this would render the pipelines harder to replicate.
