### ISSUE TITLE
Upgrading from 2.2.0 to 2.2.0 broken tests

### ISSUE THREAD

**Issue by David-Wobrock** [CircleCI-Public/go-orb#98]
Our CI job using `go/test` from this Orb started breaking when we upgrading the version from 2.2.0 to 2.2.2 - which is not expected for a patch version I reckon.

The error we get in CircleCI is:
```
stat max_parallelism/main.go: no such file or directory
```

Probably introduced by https://github.com/CircleCI-Public/go-orb/pull/94

**Comment by david-montano-circleci** [comment]
Hello @David-Wobrock . Thank you for reporting this.
I can see now how this can fail and cause issues.
I will try to replicate the problem and fix it ASAP.

**Comment by david-montano-circleci** [comment]
I created a [PR](https://github.com/CircleCI-Public/go-orb/pull/99) for this so this will open an internal discussion and hopefully we will fix this.

**Comment by david-montano-circleci** [comment]
This is fixed now in v2.2.3.
Thank you for reporting @David-Wobrock !
